namespace: node-app
# commonLabels:
#   app: node-app
resources:
  - ../../base/apps/be
  - ../../base/apps/fe
  - ../../base/apps/mongo
  - be-ingress.yaml
  - fe-ingress.yaml
  - be-cm.yaml
patchesStrategicMerge:
  - be-deploy.yaml
  - fe-deploy.yaml
images:
  - name: obusorezekiel/e-commerce-front-end
    newTag: d7ca58953c20a4144b80f59c2bcdfe71a6ff5979
  - name: obusorezekiel/e-commerce-back-end
    newTag: 8f57dcabb442aafba810f645516de82bf692191f
